// Code generated by protoc-gen-go.
// source: zplay_adx_rtb.proto
// DO NOT EDIT!

/*
Package zadx is a generated protocol buffer package.

It is generated from these files:
	zplay_adx_rtb.proto

It has these top-level messages:
*/
package zadx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import zadx1 "./"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_Version = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest)(nil),
	ExtensionType: (*int32)(nil),
	Field:         200,
	Name:          "zadx.version",
	Tag:           "varint,200,opt,name=version",
}

var E_IsPing = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest)(nil),
	ExtensionType: (*bool)(nil),
	Field:         202,
	Name:          "zadx.is_ping",
	Tag:           "varint,202,opt,name=is_ping",
}

var E_NeedHttps = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest)(nil),
	ExtensionType: (*bool)(nil),
	Field:         203,
	Name:          "zadx.need_https",
	Tag:           "varint,203,opt,name=need_https",
}

var E_Accu = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Geo)(nil),
	ExtensionType: (*int32)(nil),
	Field:         200,
	Name:          "zadx.accu",
	Tag:           "varint,200,opt,name=accu",
}

var E_Street = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Geo)(nil),
	ExtensionType: (*string)(nil),
	Field:         201,
	Name:          "zadx.street",
	Tag:           "bytes,201,opt,name=street",
}

var E_IsSplashScreen = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Imp)(nil),
	ExtensionType: (*bool)(nil),
	Field:         200,
	Name:          "zadx.is_splash_screen",
	Tag:           "varint,200,opt,name=is_splash_screen",
}

var E_InventoryTypes = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Imp)(nil),
	ExtensionType: ([]int32)(nil),
	Field:         201,
	Name:          "zadx.inventory_types",
	Tag:           "varint,201,rep,name=inventory_types",
}

var E_AdType = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Imp)(nil),
	ExtensionType: (*int32)(nil),
	Field:         202,
	Name:          "zadx.ad_type",
	Tag:           "varint,202,opt,name=ad_type",
}

var E_TagName = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Imp)(nil),
	ExtensionType: (*string)(nil),
	Field:         203,
	Name:          "zadx.tag_name",
	Tag:           "bytes,203,opt,name=tag_name",
}

var E_Plmn = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         200,
	Name:          "zadx.plmn",
	Tag:           "bytes,200,opt,name=plmn",
}

var E_Imei = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         201,
	Name:          "zadx.imei",
	Tag:           "bytes,201,opt,name=imei",
}

var E_Mac = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         202,
	Name:          "zadx.mac",
	Tag:           "bytes,202,opt,name=mac",
}

var E_AndroidId = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         203,
	Name:          "zadx.android_id",
	Tag:           "bytes,203,opt,name=android_id",
}

var E_Adid = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         204,
	Name:          "zadx.adid",
	Tag:           "bytes,204,opt,name=adid",
}

var E_Orientation = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*int32)(nil),
	Field:         205,
	Name:          "zadx.orientation",
	Tag:           "varint,205,opt,name=orientation",
}

var E_Imsi = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         206,
	Name:          "zadx.imsi",
	Tag:           "bytes,206,opt,name=imsi",
}

var E_Idfv = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         207,
	Name:          "zadx.idfv",
	Tag:           "bytes,207,opt,name=idfv",
}

var E_Imptrackers = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: ([]string)(nil),
	Field:         200,
	Name:          "zadx.imptrackers",
	Tag:           "bytes,200,rep,name=imptrackers",
}

var E_Clktrackers = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: ([]string)(nil),
	Field:         201,
	Name:          "zadx.clktrackers",
	Tag:           "bytes,201,rep,name=clktrackers",
}

var E_Clkurl = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         202,
	Name:          "zadx.clkurl",
	Tag:           "bytes,202,opt,name=clkurl",
}

var E_HtmlSnippet = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         203,
	Name:          "zadx.html_snippet",
	Tag:           "bytes,203,opt,name=html_snippet",
}

var E_AppVer = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         204,
	Name:          "zadx.app_ver",
	Tag:           "bytes,204,opt,name=app_ver",
}

var E_InventoryType = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*int32)(nil),
	Field:         205,
	Name:          "zadx.inventory_type",
	Tag:           "varint,205,opt,name=inventory_type",
}

var E_Title = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         206,
	Name:          "zadx.title",
	Tag:           "bytes,206,opt,name=title",
}

var E_Desc = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         207,
	Name:          "zadx.desc",
	Tag:           "bytes,207,opt,name=desc",
}

var E_Action = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*int32)(nil),
	Field:         208,
	Name:          "zadx.action",
	Tag:           "varint,208,opt,name=action",
}

var E_DownloadFileName = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         209,
	Name:          "zadx.download_file_name",
	Tag:           "bytes,209,opt,name=download_file_name",
}

var E_PlayStartTrackers = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: ([]string)(nil),
	Field:         210,
	Name:          "zadx.play_start_trackers",
	Tag:           "bytes,210,rep,name=play_start_trackers",
}

var E_PlayEndTrackers = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: ([]string)(nil),
	Field:         211,
	Name:          "zadx.play_end_trackers",
	Tag:           "bytes,211,rep,name=play_end_trackers",
}

var E_FallbackUrl = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         212,
	Name:          "zadx.fallback_url",
	Tag:           "bytes,212,opt,name=fallback_url",
}

var E_FallbackAction = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*int32)(nil),
	Field:         213,
	Name:          "zadx.fallback_action",
	Tag:           "varint,213,opt,name=fallback_action",
}

var E_LinkType = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.NativeResponse_Link)(nil),
	ExtensionType: (*int32)(nil),
	Field:         200,
	Name:          "zadx.link_type",
	Tag:           "varint,200,opt,name=link_type",
}

var E_Fallback = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.NativeResponse_Link)(nil),
	ExtensionType: (*string)(nil),
	Field:         201,
	Name:          "zadx.fallback",
	Tag:           "bytes,201,opt,name=fallback",
}

var E_FallbackUrlAction = &proto.ExtensionDesc{
	ExtendedType:  (*zadx1.NativeResponse_Link)(nil),
	ExtensionType: (*int32)(nil),
	Field:         202,
	Name:          "zadx.fallback_url_action",
	Tag:           "varint,202,opt,name=fallback_url_action",
}

func init() {
	proto.RegisterExtension(E_Version)
	proto.RegisterExtension(E_IsPing)
	proto.RegisterExtension(E_NeedHttps)
	proto.RegisterExtension(E_Accu)
	proto.RegisterExtension(E_Street)
	proto.RegisterExtension(E_IsSplashScreen)
	proto.RegisterExtension(E_InventoryTypes)
	proto.RegisterExtension(E_AdType)
	proto.RegisterExtension(E_TagName)
	proto.RegisterExtension(E_Plmn)
	proto.RegisterExtension(E_Imei)
	proto.RegisterExtension(E_Mac)
	proto.RegisterExtension(E_AndroidId)
	proto.RegisterExtension(E_Adid)
	proto.RegisterExtension(E_Orientation)
	proto.RegisterExtension(E_Imsi)
	proto.RegisterExtension(E_Idfv)
	proto.RegisterExtension(E_Imptrackers)
	proto.RegisterExtension(E_Clktrackers)
	proto.RegisterExtension(E_Clkurl)
	proto.RegisterExtension(E_HtmlSnippet)
	proto.RegisterExtension(E_AppVer)
	proto.RegisterExtension(E_InventoryType)
	proto.RegisterExtension(E_Title)
	proto.RegisterExtension(E_Desc)
	proto.RegisterExtension(E_Action)
	proto.RegisterExtension(E_DownloadFileName)
	proto.RegisterExtension(E_PlayStartTrackers)
	proto.RegisterExtension(E_PlayEndTrackers)
	proto.RegisterExtension(E_FallbackUrl)
	proto.RegisterExtension(E_FallbackAction)
	proto.RegisterExtension(E_LinkType)
	proto.RegisterExtension(E_Fallback)
	proto.RegisterExtension(E_FallbackUrlAction)
}
